SELECT
	B.CODFILIAL,
	B.CODAUXILIAR,
	P.CODPROD,
	P.DESCRICAO,
	P.UNIDADE,
	P.EMBALAGEM,
	D.CODEPTO,
	D.DESCRICAO AS DEPARTAMENTO,
	ROUND(E.CUSTOULTENT, 2) AS CUSTOULTENT,
	ROUND(E.CUSTOFIN, 2) AS CUSTOFIN,
	ROUND(B.PVENDA, 2) AS PVENDA,
	ROUND(B.PVENDAATAC, 2) AS PVENDAATAC,
	E.QTESTGER AS ESTOQUE,
	SUM(E.QTESTGER) OVER (PARTITION BY P.CODPROD) AS ESTOQUE_GERAL,
	ROUND(E.QTGIRODIA, 2) AS QTGIRODIA,
	E.DTULTENT,
	E.DTULTSAIDA,
	PF.ATIVO
FROM
	PCPRODUT P,
	PCEMBALAGEM B,
	PCEST E,
	PCDEPTO D,
	PCPRODFILIAL PF
WHERE
	P.CODPROD = B.CODPROD
	AND P.CODEPTO = D.CODEPTO
	AND B.CODPROD = E.CODPROD
	AND B.CODFILIAL = E.CODFILIAL
	AND B.CODPROD = PF.CODPROD
	AND B.CODFILIAL = PF.CODFILIAL
	AND P.CODPROD = :codprod
ORDER BY
	B.CODFILIAL