@url = http://localhost:3000
@token = {{authenticate.response.body.accessToken}}

#Auth
### authenticate
# @name authenticate
POST {{url}}/auth/login
Content-Type: application/json

{
  "NOME": "pcadmin",
  "SENHA": "5500"
}
###

# USUARIOS
###
GET {{url}}/usuario
admgestao: {{token}}
###
GET {{url}}/usuario/127
admgestao: {{token}}
###
POST {{url}}/usuario
Content-Type: application/json

{
  "CODUSUARIO": "1",
  "NOME": "pcadmin",
  "SENHA": "5500",
  "ROUTEPOLICIES": ["getUsuario", "upsertUsuario"],
  "EMAIL": "admin@gmail.com"
}
###
PATCH {{url}}/usuario/127
Content-Type: application/json

{
  "NOME": "lucas",
  "ACTIVE": 1
}
###

# TELEGRAM
###
GET {{url}}/telegram

# EMAIL
###
GET {{url}}/email