WITH PEDIDO AS (
    SELECT
        PCPEDIDO.DTEMISSAO DATA,
        PCEMPR.NOME,
        PCPEDIDO.NUMPED,
        PCPEDIDO.CODFORNEC,
        PCFORNEC.FORNECEDOR,
        PCPEDIDO.VLTOTAL VLRGASTO,
        PCPEDIDO.CODCONTA,
        PCLANC3.RECNUM,
        PCLIMITECOMPRAPERIODO.CODCOMPRADOR,
        NVL(PCLIMITECOMPRAPERIODO.CODFILIAL, PCPEDIDO.CODFILIAL) AS CODFILIAL
    FROM
        PCLIMITECOMPRAPERIODO,
        PCEMPR,
        PCFORNEC,
        PCPEDIDO,
        PCLANC3
    WHERE
        NVL(PCLIMITECOMPRAPERIODO.VALORLIMITE, 0) >= 0
        AND 'P' = 'P'
        AND PCLIMITECOMPRAPERIODO.CODCOMPRADOR = PCEMPR.MATRICULA(+)
        AND PCFORNEC.CODFORNEC = PCPEDIDO.CODFORNEC
        AND PCPEDIDO.TIPOBONIFIC <> 'B'
        AND NVL(PCLIMITECOMPRAPERIODO.CODCOMPRADOR, PCPEDIDO.CODCOMPRADOR) = PCPEDIDO.CODCOMPRADOR
        AND PCPEDIDO.NUMPED = PCLANC3.NUMPED(+)
        AND NVL(PCLIMITECOMPRAPERIODO.CODFILIAL, PCPEDIDO.CODFILIAL) = PCPEDIDO.CODFILIAL
        AND PCPEDIDO.DTEMISSAO BETWEEN PCLIMITECOMPRAPERIODO.DATAINICIAL AND PCLIMITECOMPRAPERIODO.DATAFINAL
        AND (
            (
                (:dataInicio BETWEEN PCLIMITECOMPRAPERIODO.DATAINICIAL AND PCLIMITECOMPRAPERIODO.DATAFINAL)
                OR (:dataFim BETWEEN PCLIMITECOMPRAPERIODO.DATAINICIAL AND PCLIMITECOMPRAPERIODO.DATAFINAL)
            )
            OR (
                (PCLIMITECOMPRAPERIODO.DATAINICIAL BETWEEN :dataInicio AND :dataFim)
                OR (PCLIMITECOMPRAPERIODO.DATAFINAL BETWEEN :dataFim AND :dataFim)
            )
        )

    UNION

    SELECT
        PCLANC3.DTVENC DATA,
        PCEMPR.NOME,
        PCLANC3.NUMPED,
        PCLANC3.CODFORNEC,
        PCFORNEC.FORNECEDOR,
        PCLANC3.VALOR VLRGASTO,
        PCPEDIDO.CODCONTA,
        PCLANC3.RECNUM,
        PCLIMITECOMPRAPERIODO.CODCOMPRADOR,
        NVL(PCLIMITECOMPRAPERIODO.CODFILIAL, PCPEDIDO.CODFILIAL) AS CODFILIAL
    FROM
        PCLIMITECOMPRAPERIODO,
        PCEMPR,
        PCFORNEC,
        PCLANC3,
        PCPEDIDO
    WHERE
        NVL(PCLIMITECOMPRAPERIODO.VALORLIMITE, 0) >= 0
        AND 'P' = 'C'
        AND PCLIMITECOMPRAPERIODO.CODCOMPRADOR = PCEMPR.MATRICULA(+)
        AND PCFORNEC.CODFORNEC = PCLANC3.CODFORNEC
        AND PCPEDIDO.TIPOBONIFIC <> 'B'
        AND PCPEDIDO.NUMPED = PCLANC3.NUMPED
        AND NVL(PCLIMITECOMPRAPERIODO.CODCOMPRADOR, PCPEDIDO.CODCOMPRADOR) = PCPEDIDO.CODCOMPRADOR
        AND NVL(PCLIMITECOMPRAPERIODO.CODFILIAL, PCPEDIDO.CODFILIAL) = PCPEDIDO.CODFILIAL
        AND NVL(PCLIMITECOMPRAPERIODO.CODFORNEC, PCLANC3.CODFORNEC) = PCLANC3.CODFORNEC
        AND PCLANC3.DTVENC BETWEEN PCLIMITECOMPRAPERIODO.DATAINICIAL AND PCLIMITECOMPRAPERIODO.DATAFINAL
        AND (
            (
                (:dataInicio BETWEEN PCLIMITECOMPRAPERIODO.DATAINICIAL AND PCLIMITECOMPRAPERIODO.DATAFINAL)
                OR (:dataFim BETWEEN PCLIMITECOMPRAPERIODO.DATAINICIAL AND PCLIMITECOMPRAPERIODO.DATAFINAL)
            )
            OR (
                (PCLIMITECOMPRAPERIODO.DATAINICIAL BETWEEN :dataInicio AND :dataFim)
                OR (PCLIMITECOMPRAPERIODO.DATAFINAL BETWEEN :dataFim AND :dataFim)
            )
        )

    UNION

    SELECT
        PCLANC.DTVENC DATA,
        PCEMPR.NOME,
        (
            SELECT M.NUMPED
            FROM PCMOV M
            WHERE M.NUMTRANSENT = PCNFENT.NUMTRANSENT
              AND ROWNUM <= 1
        ) NUMPED,
        PCLANC.CODFORNEC,
        PCFORNEC.FORNECEDOR,
        PCLANC.VALOR VLRGASTO,
        PCLANC.CODCONTA,
        PCLANC.RECNUM,
        PCLIMITECOMPRAPERIODO.CODCOMPRADOR,
        NVL(PCLIMITECOMPRAPERIODO.CODFILIAL, PCLANC.CODFILIAL) AS CODFILIAL
    FROM
        PCLIMITECOMPRAPERIODO,
        PCEMPR,
        PCFORNEC,
        PCLANC,
        PCCONSUM,
        PCNFENT
    WHERE
        NVL(PCLIMITECOMPRAPERIODO.VALORLIMITE, 0) >= 0
        AND NOT EXISTS (
            SELECT 1
            FROM PCDESDLANC
            WHERE PCLANC.RECNUM = PCDESDLANC.RECNUMORIG
        )
        AND 'P' = 'C'
        AND PCLIMITECOMPRAPERIODO.CODCOMPRADOR = PCEMPR.MATRICULA(+)
        AND PCFORNEC.CODFORNEC = PCLANC.CODFORNEC
        AND (
            (PCLANC.CODCONTA IN (PCCONSUM.CODCONTFOR, PCCONSUM.CODCONTFRE, PCCONSUM.CODCONTOUT))
            OR (PCNFENT.TIPODESCARGA = 'S')
        )
        AND NVL(PCLANC.NUMTRANSENTNF, PCLANC.NUMTRANSENT) = PCNFENT.NUMTRANSENT
        AND PCNFENT.CODCONT = PCNFENT.CODCONTFOR
        AND PCNFENT.DTCANCEL IS NULL
        AND PCLANC.VALOR > 0
        AND PCLANC.DTESTORNOBAIXA IS NULL
        AND PCLANC.DTCANCEL IS NULL
        AND NVL(PCLIMITECOMPRAPERIODO.CODCOMPRADOR, PCLANC.CODCOMPRADOR) = PCLANC.CODCOMPRADOR
        AND NVL(PCLIMITECOMPRAPERIODO.CODFILIAL, PCLANC.CODFILIAL) = PCLANC.CODFILIAL
        AND NVL(PCLIMITECOMPRAPERIODO.CODFORNEC, PCLANC.CODFORNEC) = PCLANC.CODFORNEC
        AND PCLANC.DTVENC BETWEEN PCLIMITECOMPRAPERIODO.DATAINICIAL AND PCLIMITECOMPRAPERIODO.DATAFINAL
        AND (
            (
                (:dataInicio BETWEEN PCLIMITECOMPRAPERIODO.DATAINICIAL AND PCLIMITECOMPRAPERIODO.DATAFINAL)
                OR (:dataFim BETWEEN PCLIMITECOMPRAPERIODO.DATAINICIAL AND PCLIMITECOMPRAPERIODO.DATAFINAL)
            )
            OR (
                (PCLIMITECOMPRAPERIODO.DATAINICIAL BETWEEN :dataInicio AND :dataFim)
                OR (PCLIMITECOMPRAPERIODO.DATAFINAL BETWEEN :dataFim AND :dataFim)
            )
        )
),
ENTREGUE AS (
    SELECT * FROM PCPEDNF
)
SELECT
    P.CODFILIAL,
    P.CODCOMPRADOR,
    P.NOME,
    P.FORNECEDOR,
    P.NUMPED,
    CASE
        WHEN E.NUMPEDIDO IS NULL THEN 'VALOR_NAO_ENTREGUE'
        ELSE 'VALOR_ENTREGUE'
    END AS STATUS_ENTREGA,
    SUM(CASE WHEN E.NUMPEDIDO IS NULL THEN P.VLRGASTO ELSE 0 END) AS VALOR_NAO_ENTREGUE,
    SUM(CASE WHEN E.NUMPEDIDO IS NOT NULL THEN P.VLRGASTO ELSE 0 END) AS VALOR_ENTREGUE
FROM
    PEDIDO P
    LEFT JOIN ENTREGUE E ON P.NUMPED = E.NUMPEDIDO
WHERE
    P.CODCOMPRADOR IS NOT NULL
    AND P.CODCOMPRADOR = :codcomprador
GROUP BY
    P.CODFILIAL,
    P.CODCOMPRADOR,
    P.NOME,
    P.FORNECEDOR,
    P.NUMPED,
    CASE
        WHEN E.NUMPEDIDO IS NULL THEN 'VALOR_NAO_ENTREGUE'
        ELSE 'VALOR_ENTREGUE'
    END
ORDER BY
    P.CODFILIAL,
    P.CODCOMPRADOR,
    P.FORNECEDOR,
     CASE
        WHEN E.NUMPEDIDO IS NULL THEN 'VALOR_NAO_ENTREGUE'
        ELSE 'VALOR_ENTREGUE'
    END