@url = http://localhost:3333/adm
@token = {{authenticate.response.body.accessToken}}

#Auth
### authenticate
# @name authenticate
POST {{url}}/auth/login
Content-Type: application/json

{
  "NOME": "pcadmin",
  "SENHA": "5500"
}
###

###
GET {{url}}/precificacao/18-FEB-2026
admgestao: {{token}}
###
GET {{url}}/precificacao/todas/18-FEB-2026
admgestao: {{token}}
###
GET {{url}}/precificacao/prevenda/16-FEB-2026
admgestao: {{token}}

###
POST {{url}}/precificacao
admgestao: {{token}}
Content-Type: application/json

{
  "COD_PRODUTO": 1,
  "PRECOMINSUG": 12.56
}


###
GET {{url}}/precificacao/pesquisa/53541
admgestao: {{token}}