WITH SAIDA AS (
	SELECT SUM(NVL(M.QT, 0)) AS TOTAL_SAIDA
	FROM PCMOV M
	WHERE M.DTMOV BETWEEN TO_DATE(:datainicio,'DD-MON-YYYY','NLS_DATE_LANGUAGE=ENGLISH') 
		AND TO_DATE(:datafim,'DD-MON-YYYY','NLS_DATE_LANGUAGE=ENGLISH')
	AND M.CODOPER = 'S'
	AND M.CODFILIAL = :filial 
	AND M.CODEPTO = 17
),
ESTOQUE AS (
	SELECT SUM(NVL(E.QTESTGER, 0)) AS ESTOQUE
	FROM PCEST E, PCPRODUT P
	WHERE E.CODPROD = P.CODPROD 
	AND P.CODEPTO = 17
	AND E.CODFILIAL = :filial 
)
SELECT * FROM SAIDA, ESTOQUE