SELECT 
    P.CODPROD, 
    P.DESCRICAO, 
    M.CODOPER,
SUM(
        CASE
            WHEN M.CODOPER = 'E' AND M.QT < 0 THEN -ABS(M.QT)
            ELSE M.QT
        END
    ) AS TOTAL_QT,
    E.QTESTGER AS ESTOQUE
FROM PCMOV M
JOIN PCPRODUT P 
    ON M.CODPROD = P.CODPROD
JOIN PCEST E 
    ON M.CODPROD = E.CODPROD 
   AND M.CODFILIAL = E.CODFILIAL 
WHERE M.DTMOV BETWEEN TO_DATE(:datainicio,'DD-MON-YYYY','NLS_DATE_LANGUAGE=ENGLISH')
                  AND TO_DATE(:datafim,'DD-MON-YYYY','NLS_DATE_LANGUAGE=ENGLISH')
  AND P.TIPOMERC = 'BC'
  AND P.CODEPTO = 17
  AND M.CODFILIAL = :filial
  AND M.CODOPER IN ('E', 'SP')
GROUP BY  
    P.CODPROD, 
    P.DESCRICAO, 
    M.CODOPER,
    E.QTESTGER 