WITH MOVIMENTOS AS (
    SELECT
        M.CODFILIAL,
        M.NUMNOTA,
        SUM(M.QT * M.PUNIT) AS VENDA,
        SUM(M.QT * M.CUSTOFIN) AS CUSTO
    FROM
        PCMOV M
    WHERE
        TRUNC(M.DTMOV) = TRUNC(SYSDATE)
        AND M.CODOPER = 'S'
    GROUP BY
        M.CODFILIAL,
        M.NUMNOTA
),
NOTAS AS (
    SELECT
        P.CODFILIAL,
        P.NUMNOTA
    FROM
        PCNFSAID P
   WHERE TRUNC(P.DTSAIDA) = TRUNC(SYSDATE)
        AND P.DTCANCEL IS NULL
        AND P.CONDVENDA IN (1, 5)
    GROUP BY
        P.CODFILIAL,
        P.NUMNOTA
),
BASE AS (
    SELECT
        M.CODFILIAL,
        M.NUMNOTA,
        M.VENDA,
        M.CUSTO
    FROM
        MOVIMENTOS M
        JOIN NOTAS N ON N.CODFILIAL = M.CODFILIAL
        AND N.NUMNOTA = M.NUMNOTA
),
NUMVENDAS AS (
    SELECT
        CODFILIAL,
        COUNT(*) AS NUMVENDAS
    FROM
        BASE
    GROUP BY
        CODFILIAL
),
VENDA AS (
    SELECT
        B.CODFILIAL,
        ROUND(SUM(B.CUSTO), 2) AS CUSTO,
        ROUND(SUM(B.VENDA), 2) AS VENDA,
        NV.NUMVENDAS,
        ROUND(SUM(B.VENDA) - SUM(B.CUSTO), 2) AS LUCRO,
        ROUND(
            SUM(B.VENDA) / NULLIF(NV.NUMVENDAS, 0),
            2
        ) AS TICKET_MEDIO,
        CASE
            WHEN SUM(B.VENDA) = 0 THEN 0
            ELSE ROUND(
                ((SUM(B.VENDA) - SUM(B.CUSTO)) * 100) / SUM(B.VENDA),
                2
            )
        END AS MARGEM
    FROM
        BASE B
        JOIN NUMVENDAS NV ON NV.CODFILIAL = B.CODFILIAL
    GROUP BY
        B.CODFILIAL,
        NV.NUMVENDAS
),
META AS (
    SELECT
        PCMETASUP.CODFILIAL,
        SUM(PCMETASUP.VLVENDAPREV) AS META
    FROM
        PCMETASUP
    WHERE
        PCMETASUP.DATA >= TRUNC(SYSDATE, 'MM')
        AND PCMETASUP.DATA < ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)
    GROUP BY
        PCMETASUP.CODFILIAL
)
SELECT
    V.*,
    NVL(M.META, 0) AS META,
    ROUND((V.VENDA / NULLIF(M.META, 0)) * 100, 2) AS PERCENTUAL_CARREGADO
FROM
    VENDA V
    LEFT JOIN META M ON V.CODFILIAL = M.CODFILIAL
ORDER BY
    V.CODFILIAL