

SELECT F.NUMPED,C.NUMCUPOM, C.SERIE, C.VALOR, C.DATA_CADASTRO, C.AVALIACAO
FROM DEVBR.CUPOMCLIENTE C
LEFT JOIN PCPEDCECF F ON C.NUMCUPOM = F.NUMCUPOM AND C.SERIE = F.NUMCAIXAFISCAL AND C.VALOR = F.VLTOTAL
WHERE C.IDUSUARIO = :idusuario