WITH VENDA AS (
    SELECT
        M.CODFILIAL,
        ROUND(SUM(M.QT * M.CUSTOFIN), 2) AS CMV,
        ROUND(SUM(M.QT * M.PUNIT), 2) AS VENDA,
        COUNT(DISTINCT M.NUMTRANSVENDA) AS QTNFS,
        ROUND(SUM(M.QT * M.PUNIT) - SUM(M.QT * M.CUSTOFIN), 2) AS LUCRO,
        ROUND(SUM(M.QT * M.PUNIT) / COUNT(DISTINCT M.NUMTRANSVENDA), 2) AS TICKET_MEDIO,
        CASE
            WHEN SUM(M.QT * M.PUNIT) = 0 THEN 0
            ELSE ROUND(((SUM(M.QT * M.PUNIT) - SUM(M.QT * M.CUSTOFIN)) * 100) / SUM(M.QT * M.PUNIT), 2)
        END AS MARGEM
    FROM PCMOV M
    WHERE M.DTMOV >= TRUNC(SYSDATE, 'MM')
      AND M.DTMOV <  ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)
      AND M.CODOPER IN ('S', 'SB')
    GROUP BY M.CODFILIAL
),
META AS (
    SELECT
        PCMETASUP.CODFILIAL,
        SUM(PCMETASUP.VLVENDAPREV) AS META
    FROM PCMETASUP
    WHERE PCMETASUP.DATA >= TRUNC(SYSDATE, 'MM')
      AND PCMETASUP.DATA <  ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)
    GROUP BY PCMETASUP.CODFILIAL
),
INFO_FILIAL AS (
    SELECT 1 CODFILIAL, 950 METRO, 13 CHECKOUTS FROM dual UNION ALL
    SELECT 2, 280,  4 FROM dual UNION ALL
    SELECT 3, 350,  5 FROM dual UNION ALL
    SELECT 4, 600,  3 FROM dual UNION ALL
    SELECT 5, 480,  6 FROM dual
),
QT_FUNCIONARIO AS (
	SELECT u.CODFILIAL, COUNT(*) AS QT_FUNCIONARIO
	FROM PCEMPR u
	WHERE u.SITUACAO = 'A'
	AND u.MATRICULA NOT IN (520,521,522,523,59,98,163,183,6,5,217,519,101,216,132,524,587,435,94)
	AND u.CODFILIAL IS NOT null
	GROUP BY u.CODFILIAL
	ORDER BY u.CODFILIAL
)
SELECT
    V.CODFILIAL,
    V.CMV,
    V.VENDA,
    V.QTNFS,
    V.LUCRO,
    V.TICKET_MEDIO,
    V.MARGEM,
    M.META,
    F.QT_FUNCIONARIO,
    I.METRO,
    I.CHECKOUTS,
    ROUND((V.VENDA / NULLIF(M.META, 0)) * 100, 2) AS PERCENTUAL_CARREGADO,
    ROUND((V.VENDA / NULLIF(SUM(V.VENDA) OVER (), 0)) * 100, 2) AS PERC_DA_VENDA
FROM VENDA V
JOIN META M ON M.CODFILIAL = V.CODFILIAL
LEFT JOIN INFO_FILIAL I ON I.CODFILIAL = V.CODFILIAL
JOIN QT_FUNCIONARIO F ON F.CODFILIAL = V.CODFILIAL
ORDER BY V.CODFILIAL
