WITH TABELA212 AS (
  SELECT 
      T.CODFUNC,
      U.NOME,
      T.DATA AS DT_LOG,
      T.CODROTINA,
      T.VALORNUMANT AS VALOR_ANTIGO,
      TO_CHAR( (FANT.PERPIS + FANT.PERCOFINS + FANT.PERCREDICMS)
             , 'FM9990D00'
             , 'NLS_NUMERIC_CHARACTERS=,.' ) AS VALOR_CREDI_ENTR_ANTIGO,
      T.VALORNUM AS VALOR_NOVO,
      TO_CHAR( (FNOV.PERPIS + FNOV.PERCOFINS + FNOV.PERCREDICMS)
             , 'FM9990D00'
             , 'NLS_NUMERIC_CHARACTERS=,.' ) AS VALOR_CREDI_ENTR_NOVO,
      T.OBSERVACOES,
      T.OBSERVACOES2
  FROM PCLOGALTERACAODADOS T
  JOIN PCEMPR U ON T.CODFUNC = U.MATRICULA
  LEFT JOIN PCTRIBFIGURA FANT ON T.VALORNUMANT = FANT.CODFIGURA
  LEFT JOIN PCTRIBFIGURA FNOV ON T.VALORNUM   = FNOV.CODFIGURA
  WHERE T.CODROTINA = 212
    AND TRUNC(T.DATA) BETWEEN TO_DATE(
        :dataInicio,
        'DD-MON-YYYY',
        'NLS_DATE_LANGUAGE=ENGLISH'
    )  AND TO_DATE(
        :datafim,
        'DD-MON-YYYY',
        'NLS_DATE_LANGUAGE=ENGLISH'
    )
    AND T.TIPOVALOR = 'N'
),
TABELA574 AS (
  SELECT 
      T.CODFUNC,
      U.NOME,
      T.DATA AS DT_LOG,
      T.CODROTINA,
      T.VALORNUMANT AS VALOR_ANTIGO,
      CAST(FANT.MENSAGEM AS VARCHAR2(400)) AS VALOR_CREDI_ENTR_ANTIGO,
      T.VALORNUM AS VALOR_NOVO,
      CAST(FNOV.MENSAGEM AS VARCHAR2(400)) AS VALOR_CREDI_ENTR_NOVO,
      T.OBSERVACOES,
      T.OBSERVACOES2
  FROM PCLOGALTERACAODADOS T
  JOIN PCEMPR U ON T.CODFUNC = U.MATRICULA
  LEFT JOIN PCTRIBUT FANT ON T.VALORNUMANT = FANT.CODST
  LEFT JOIN PCTRIBUT FNOV ON T.VALORNUM   = FNOV.CODST
  WHERE T.CODROTINA = 574
    AND TRUNC(T.DATA) BETWEEN TO_DATE(
        :dataInicio,
        'DD-MON-YYYY',
        'NLS_DATE_LANGUAGE=ENGLISH'
    )  AND TO_DATE(
        :datafim,
        'DD-MON-YYYY',
        'NLS_DATE_LANGUAGE=ENGLISH'
    )
    AND T.TIPOVALOR = 'N'
)
SELECT 
  CODFUNC, NOME, DT_LOG, CODROTINA,
  VALOR_ANTIGO, VALOR_CREDI_ENTR_ANTIGO,
  VALOR_NOVO,   VALOR_CREDI_ENTR_NOVO,
  OBSERVACOES,  OBSERVACOES2
FROM TABELA212
UNION ALL
SELECT 
  CODFUNC, NOME, DT_LOG, CODROTINA,
  VALOR_ANTIGO, VALOR_CREDI_ENTR_ANTIGO,
  VALOR_NOVO,   VALOR_CREDI_ENTR_NOVO,
  OBSERVACOES,  OBSERVACOES2
FROM TABELA574
ORDER BY DT_LOG, CODROTINA, CODFUNC
