/* Relatório PCLANC x PCCONTA – mês atual automático */
WITH
-- Janela do mês atual (fim exclusivo) + ano/mês correntes
params AS (
  SELECT
    TRUNC(SYSDATE, 'MM')                          AS ini,
    ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)           AS fim_ex,
    TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'))           AS ano,
    TO_NUMBER(TO_CHAR(SYSDATE, 'MM'))             AS mes
  FROM dual
),

/* Filtros comuns de lançamentos */
base_lanc AS (
  SELECT
    L.*,
    N.CONDVENDA,
    NVL(N.CODFISCAL, 0) AS CODFISCAL
  FROM PCLANC L
  LEFT JOIN PCNFSAID N
    ON N.NUMTRANSVENDA = L.NUMTRANSVENDA
  WHERE L.CODFILIAL IN ('1','2','3','4','5','99')
    AND L.CODCONTA NOT IN (250009, 250016, 250013)
    AND NVL(L.CODROTINABAIXA, 0) <> 737
    -- excluir contratos TIPOC=6 baixados por 772
    AND NOT EXISTS (
      SELECT 1
      FROM PCCONTRATOEMPRESTIMO C, PCLANC LC
      WHERE C.NUMSEQCONTRATOEMPRESTIMO = LC.NUMSEQCONTRATOEMPRESTIMO
        AND C.TIPOCONTRATO = 6
        AND NVL(LC.CODROTINABAIXA, 0) = 772
        AND LC.RECNUM = L.RECNUM
    )
    -- excluir estorno casado com venda condvenda=20
    AND NOT EXISTS (
      SELECT 1
      FROM PCESTCOM D
      JOIN PCNFSAID N2 ON N2.NUMTRANSVENDA = D.NUMTRANSVENDA
      WHERE D.NUMTRANSENT = L.NUMTRANSENT
        AND D.DTESTORNO  = L.DTLANC
        AND N2.CONDVENDA IN (20)
    )
),

/* PREVISTO: títulos em aberto cujo vencimento cai no mês */
previsto AS (
  SELECT
    B.CODCONTA,
    NVL(SUM(B.VALOR), 0) * (-1) AS VLPREVISTO
  FROM base_lanc B
  CROSS JOIN params P
  WHERE B.DTPAGTO IS NULL
    AND B.DTVENC >= P.ini
    AND B.DTVENC <  P.fim_ex
    AND NVL(B.VALOR, 0) <> 0
    AND NVL(B.CONDVENDA, 0) NOT IN (10, 20, 98, 99)
    AND NVL(B.CODFISCAL, 0) NOT IN (522,622,722,532,632,732)
  GROUP BY B.CODCONTA
),

/* REALIZADO (parte 1): baixas pagas dentro do mês */
realizado_baixas AS (
  SELECT
    B.CODCONTA,
    NVL(SUM(
      CASE
        WHEN NVL(B.VPAGO, 0) = 0 THEN
          CASE
            WHEN B.DESCONTOFIN = B.VALOR THEN B.VALOR
            WHEN NVL(B.VALORDEV, 0) = B.VALOR THEN B.VALOR
            ELSE 0
          END
        ELSE NVL(B.VPAGO, 0) + NVL(B.VALORDEV, 0)
      END
    ), 0) * (-1) AS VLREALIZADO
  FROM base_lanc B
  CROSS JOIN params P
  WHERE B.DTPAGTO IS NOT NULL
    AND B.DTPAGTO >= P.ini
    AND B.DTPAGTO <  P.fim_ex
    AND NVL(B.VPAGO, 0) <> 0
    AND (
         NVL(B.CONDVENDA, 0) NOT IN (10, 20, 98, 99)
     AND ( NVL(B.CODFISCAL, 0) NOT IN (522,622,722,532,632,732)
           OR TO_CHAR(B.CODCONTA) IN (
                SELECT VALOR FROM PCPARAMFILIAL
                WHERE NOME = 'CON_CODCONTRECJUR'
              )
         )
    )
  GROUP BY B.CODCONTA
),

/* REALIZADO (parte 2): adiantamentos a fornecedores no mês */
realizado_adiant AS (
  SELECT
    LA.CODCONTA,
    SUM( (BA.VPAGO + NVL(BA.VLVARIACAOCAMBIAL, 0) + NVL(BA.TXPERM, 0)) - NVL(BA.DESCONTOFIN, 0) ) AS VLREALIZADO
  FROM PCLANCADIANTFORNEC A
  JOIN PCLANC LA ON LA.RECNUM = A.RECNUMADIANTAMENTO
  JOIN PCLANC BA ON BA.RECNUM = A.RECNUMPAGTO
  CROSS JOIN params P
  WHERE A.DTESTORNO IS NULL
    AND A.DTLANC >= P.ini
    AND A.DTLANC <  P.fim_ex
    AND LA.CODFILIAL IN ('1','2','3','4','5','99')
    AND BA.DTPAGTO IS NOT NULL
    AND BA.DTESTORNOBAIXA IS NULL
    AND EXISTS (
      SELECT 1 FROM PCCONSUM C
      WHERE LA.CODCONTA IN (C.CODCONTAADIANTFOR, C.CODCONTAADIANTFOROUTROS)
    )
  GROUP BY LA.CODCONTA
),

/* REALIZADO total por conta */
realizado AS (
  SELECT CODCONTA, SUM(VLREALIZADO) AS VLREALIZADO
  FROM (
    SELECT CODCONTA, VLREALIZADO FROM realizado_baixas
    UNION ALL
    SELECT CODCONTA, VLREALIZADO FROM realizado_adiant
  )
  GROUP BY CODCONTA
),

/* ORÇAMENTO do mês corrente (pega só o mês atual) */
orc AS (
  SELECT
    A.GRUPOCONTA,
    A.CODCONTA,
    CASE TO_NUMBER(TO_CHAR(SYSDATE, 'MM'))
      WHEN 1  THEN O.VLORCMES01
      WHEN 2  THEN O.VLORCMES02
      WHEN 3  THEN O.VLORCMES03
      WHEN 4  THEN O.VLORCMES04
      WHEN 5  THEN O.VLORCMES05
      WHEN 6  THEN O.VLORCMES06
      WHEN 7  THEN O.VLORCMES07
      WHEN 8  THEN O.VLORCMES08
      WHEN 9  THEN O.VLORCMES09
      WHEN 10 THEN O.VLORCMES10
      WHEN 11 THEN O.VLORCMES11
      WHEN 12 THEN O.VLORCMES12
    END AS ORCAMENTO
  FROM PCORCLAN O
  JOIN PCCONTA A ON A.CODCONTA = O.CODCONTA
  CROSS JOIN params P
  WHERE O.ANO = P.ano
    AND O.CODFILIAL IN ('1','2','3','4','5','99')
    AND EXISTS (
      SELECT 1
      FROM base_lanc B
      WHERE B.CODCONTA = A.CODCONTA
        AND (
             (B.DTPAGTO IS NOT NULL AND B.DTPAGTO >= P.ini AND B.DTPAGTO < P.fim_ex AND NVL(B.VPAGO,0) <> 0)
          OR (B.DTPAGTO IS NULL   AND B.DTVENC >= P.ini AND B.DTVENC < P.fim_ex AND NVL(B.VALOR,0) <> 0)
        )
    )
),
META AS (
  SELECT SUM(VLVENDAPREV) AS META
  FROM PCMETASUP
  WHERE DATA >= TRUNC(SYSDATE, 'MM')
    AND DATA <  ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)
),

PREPARACAO AS (
SELECT
  C.GRUPOCONTA,
  G.GRUPO,
  SUM(NVL(P.VLPREVISTO, 0))  AS VLPREVISTO,
  ( SUM(NVL(R.VLREALIZADO, 0)) * -1 ) AS VLREALIZADO,
  CASE C.GRUPOCONTA
    WHEN 220 THEN 9
    WHEN 230 THEN 5
    WHEN 240 THEN 1
    WHEN 310 THEN 0
    WHEN 320 THEN 1.5
    WHEN 330 THEN 1.5
    WHEN 340 THEN 0
    WHEN 420 THEN 0
    WHEN 430 THEN 0
    WHEN 520 THEN 0.5
    WHEN 895 THEN 0.5
    ELSE 0
  END                        AS PORCENTAGEM,
  MAX(M.META)                AS META
FROM PCCONTA C
JOIN PCGRUPO G    ON G.CODGRUPO = C.GRUPOCONTA
LEFT JOIN previsto  P ON P.CODCONTA = C.CODCONTA
LEFT JOIN realizado R ON R.CODCONTA = C.CODCONTA
LEFT JOIN orc       ON orc.CODCONTA = C.CODCONTA
CROSS JOIN META M
WHERE C.GRUPOCONTA BETWEEN 200 AND 900
  AND NVL(C.INVESTIMENTO, 'N') <> 'S'
  AND NVL(C.RESTRINGIRNOBALANCETE, 'N') = 'N'
  AND C.CODCONTA NOT IN (250009, 250016, 250013)
  AND NVL(C.VERBA, 'N') = 'N'
GROUP BY
  C.GRUPOCONTA,
  G.GRUPO
HAVING
  SUM(NVL(P.VLPREVISTO, 0)) <> 0
  OR
  SUM(NVL(R.VLREALIZADO, 0)) <> 0
ORDER BY C.GRUPOCONTA
)

SELECT 
  P.META,
  P.GRUPOCONTA,
  P.GRUPO,
  P.VLPREVISTO,
  P.VLREALIZADO,
  P.PORCENTAGEM,
  ROUND( NVL(P.META,0) * (NVL(P.PORCENTAGEM,0) / 100), 2 ) AS ORCAMENTO,
  CASE 
    WHEN NVL(P.PORCENTAGEM,0) = 0 
      THEN ROUND( NVL(P.VLREALIZADO,0), 2 )         -- se % = 0, mostra VLREALIZADO
    ELSE
      ROUND( ( NVL(P.META,0) * (NVL(P.PORCENTAGEM,0) / 100) ) - NVL(P.VLREALIZADO,0), 2 )
  END AS SALDO
FROM PREPARACAO P