SELECT U.IDUSUARIO, U.NOME, U.CPF, U.TELEFONE, U.BAIRRO
FROM DEVBR.CUPOMCLIENTE C
LEFT JOIN DEVBR.USUARIO U ON C.IDUSUARIO = U.IDUSUARIO
WHERE C.JA_IMPRESSO = 'N'
--ORDER BY DBMS_RANDOM.VALUE
--FETCH FIRST 1 ROWS ONLY